### ISSUE TITLE
Unable to use Action

### ISSUE THREAD

**Issue by tim-mardesen** [botoapp/deploy-lambda-image-action#1]
With this action added to my current pipeline, it fails even before attempting to execute. 

[Error : .github#L1](https://github.com/Rantizo-Software/telemetry-dji/commit/d24973708c2fe23bb65e845e452a35b87be4081d#annotation_2712646395)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref

This is in reference not to the image I specify, but actually specifying what GH Action the runner should fetch. Is it possible I need to add the version to the line? Something like `- uses: botoapp/deploy-lambda-image-action@master` ?

**Comment by elmurci** [comment]
hi @tim-mardesen 

can you try something like this?

```
      - name: deploy to aws
        uses: botoapp/deploy-lambda-image-action@main
        with:
          LAMBDA_FUNCTION_NAME: ${{needs.build_and_push.outputs.botoPath}}
          ECR_IMAGE_URI: ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-2.amazonaws.com/${{xxx_path}}:latest
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
```
